# Game frames_per_second constants from: https://liquipedia.net/starcraft2/Game_Speed
MAP_SPEED = {
    'Slower': 0.6,
    'Slow': 0.8,
    'Normal': 1.0,
    'Fast': 1.2,
    'Faster': 1.4,
}

# Adapted from: https://github.com/IBM/starcraft2-replay-analysis/blob/master/notebooks/starcraft2_replay_analysis.ipynb

# Establish some unit and building groups

VESPENE_UNITS = ["Assimilator", "Extractor", "Refinery"]

SUPPLY_UNITS = ["Overlord", "Overseer", "Pylon", "SupplyDepot"]

WORKER_UNITS = ["Drone", "Probe", "SCV", "MULE"]

BASE_UNITS = ["CommandCenter", "Nexus", "Hatchery", "Lair", "Hive", "PlanetaryFortress", "OrbitalCommand"]

GROUND_UNITS = ["Barracks", "Factory", "GhostAcademy", "Armory", "RoboticsBay", "RoboticsFacility", "TemplarArchive",
                "DarkShrine", "WarpGate", "SpawningPool", "RoachWarren", "HydraliskDen", "BanelingNest", "UltraliskCavern",
                "LurkerDen", "InfestationPit",
                "Gateway"] # Additions

AIR_UNITS = ["Starport", "FusionCore", "RoboticsFacility", "Stargate", "FleetBeacon", "Spire", "GreaterSpire"]

TECH_UNITS = ["EngineeringBay", "Armory", "GhostAcademy", "TechLab", "FusionCore", "Forge", "CyberneticsCore",
              "TwilightCouncil", "RoboticsFacility", "RoboticsBay", "FleetBeacon", "TemplarArchive", "DarkShrine",
              "SpawningPool", "RoachWarren", "HydraliskDen", "BanelingNest", "UltraliskCavern", "LurkerDen", "Spire",
              "GreaterSpire", "EvolutionChamber", "InfestationPit",
              "BarracksReactor", "BarracksTechLab", "FactoryReactor", "FactoryTechLab", "StarportReactor", "StarportTechLab", # Additional building-specific addons
              "Reactor"] # Missing addon

STATIC_UNITS = ["NydusWorm", "NydusNetwork", "MissileTurret", "SpineCrawler", "SporeCrawler", "PhotonCannon", "Bunker", "SensorTower", "ShieldBattery"] # Additional static defences

ARMY_UNITS = ["Marine", "Colossus", "InfestorTerran", "Baneling", "Mothership", "MothershipCore", "Changeling", "SiegeTank", "Viking", "Reaper",
              "Ghost", "Marauder", "Thor", "Hellion", "Hellbat", "Cyclone", "Liberator", "Medivac", "Banshee", "Raven", "Battlecruiser", "Nuke", "Zealot",
              "Stalker", "HighTemplar", "Disruptor", "DarkTemplar", "Sentry", "Phoenix", "Carrier", "Oracle", "VoidRay", "Tempest", "WarpPrism", "Observer",
              "Immortal", "Adept", "Zergling", "Overlord", "Hydralisk", "Mutalisk", "Ultralisk", "Roach", "Infestor", "Corruptor",
              "BroodLord", "Queen", "Overseer", "Archon", "Broodling", "InfestedTerran", "Ravager", "Viper", "SwarmHost",
              "WidowMine", "Lurker"] # Additional lotv units

ARMY_AIR = ["Mothership", "MothershipCore", "Viking", "Liberator", "Medivac", "Banshee", "Raven", "Battlecruiser",
            "Viper", "Mutalisk", "Phoenix", "Oracle", "Carrier", "VoidRay", "Tempest", "Observer", "WarpPrism", "BroodLord",
            "Corruptor", "Observer", "Overseer"]

ARMY_GROUND = [k for k in ARMY_UNITS if k not in ARMY_AIR]

# Adapted from: https://github.com/StoicLoofah/spawningtool/blob/master/spawningtool/lotv_constants.py
# With some cleanups on spelling errors, also replicated in icon_mapping.py to map to icon images for visualization

STRUCTURES = set([
    'Armory',
    'Assimilator',
    'BanelingNest',
    'Barracks',
    'BarracksReactor',
    'BarracksTechLab',
    'Bunker',
    'CommandCenter',
    'Creeptumor',
    'CyberneticsCore',
    'DarkShrine',
    'EngineeringBay',
    'EvolutionChamber',
    'Extractor',
    'Factory',
    'FactoryReactor',
    'FactoryTechLab',
    'FleetBeacon',
    'Forge',
    'FusionCore',
    'Gateway',
    'GhostAcademy',
    'GreaterSpire',
    'Hatchery',
    'Hive',
    'HydraliskDen',
    'InfestationPit',
    'Lair',
    'LurkerDen',
    'MissileTurret',
    'Nexus',
    'NydusCanal',
    'NydusNetwork',
    'NydusWorm',
    'OrbitalCommand',
    'PhotonCannon',
    'PlanetaryFortress',
    'Pylon',
    'Reactor',
    'Refinery',
    'RoachWarren',
    'RoboticsBay',
    'RoboticsFacility',
    'SensorTower',
    'ShieldBattery',
    'SpawningPool',
    'SpineCrawler',
    'Spire',
    'SporeCrawler',
    'Stargate',
    'Starport',
    'StarportReactor',
    'StarportTechLab',
    'SupplyDepot',
    'TechLab',
    'TemplarArchive',
    'TwilightCouncil',
    'UltraliskCavern',
    'WarpGate',
])
UNITS = set([
    'Adept',
    'Archon',
    'Baneling',
    'Banshee',
    'BattleHellion',
    'Battlecruiser',
    'BroodLord',
    'Carrier',
    'Colossus',
    'Corruptor',
    'Cyclone',
    'DarkTemplar',
    'Disruptor',
    'Drone',
    'Ghost',
    'Hellbat',
    'Hellion',
    'HighTemplar',
    'Hydralisk',
    'Immortal',
    'Infestor',
    'Liberator',
    'Lurker',
    'LurkerMPEgg',
    'Marauder',
    'Marine',
    'Medivac',
    'Mothership',
    'MothershipCore',
    'MULE',
    'Mutalisk',
    'Nuke',
    'Observer',
    'Oracle',
    'Overlord',
    'Overseer',
    'Phoenix',
    'Probe',
    'Queen',
    'Ravager',
    'RavagerCocoon',
    'Raven',
    'Reaper',
    'Roach',
    'SCV',
    'Sentry',
    'SiegeTank',
    'Stalker',
    'SwarmHost',
    'Tempest',
    'Thor',
    'Ultralisk',
    'Viking',
    'VikingAssault',
    'VikingFighter',
    'Viper',
    'VoidRay',
    'WarpPrism',
    'WidowMine',
    'Zealot',
    'Zergling',
])
UPGRADES = set([
    'AdeptPiercingAttack',
    'AdeptShieldUpgrade',
    'AnabolicSynthesis',
    'BansheeCloak',
    'BansheeSpeed',
    'BattlecruiserBehemothReactor',
    'BattlecruiserEnableSpecializations',
    'Blink',
    'Burrow',
    'CarrierLaunchSpeedUpgrade',
    'CentrificalHooks',
    'Charge',
    'ChitinousPlating',
    'CycloneAirUpgrade',
    'CycloneLockOnDamageUpgrade',
    'CycloneLockOnRangeUpgrade',
    'CycloneRapidFireLaunchers',
    'DarkTemplarBlinkUpgrade',
    'DiggingClaws',
    'DrillClaws',
    'DurableMaterials',
    'EnhancedShockwaves',
    'EvolveGroovedSpines',
    'EvolveMuscularAugments',
    'ExtendedThermalLance',
    'FlyingLocusts',
    'GhostMoebiusReactor',
    'GlialReconstitution',
    'GraviticDrive',
    'HiSecAutoTracking',
    'HighCapacityBarrels',
    'HydraliskSpeedUpgrade',
    'HyperflightRotors',
    'InfestorEnergyUpgrade',
    'LiberatorAGRangeUpgrade',
    'LocustLifetimeIncrease',
    'LurkerRange',
    'MagFieldLaunchers',
    'MedivacCaduceusReactor',
    'MedivacIncreaseSpeedBoost',
    'MicrobialShroud',
    'NeosteelFrame',
    'NeuralParasite',
    'ObserverGraviticBooster',
    'PersonalCloaking',
    'PhoenixRangeUpgrade',
    'ProtossAirArmorsLevel1',
    'ProtossAirArmorsLevel2',
    'ProtossAirArmorsLevel3',
    'ProtossAirWeaponsLevel1',
    'ProtossAirWeaponsLevel2',
    'ProtossAirWeaponsLevel3',
    'ProtossGroundArmorsLevel1',
    'ProtossGroundArmorsLevel2',
    'ProtossGroundArmorsLevel3',
    'ProtossGroundWeaponsLevel1',
    'ProtossGroundWeaponsLevel2',
    'ProtossGroundWeaponsLevel3',
    'ProtossShieldsLevel1',
    'ProtossShieldsLevel2',
    'ProtossShieldsLevel3',
    'PsiStormTech',
    'PunisherGrenades',
    'RavenCorvidReactor',
    'RavenDamageUpgrade',
    'RavenEnhancedMunitions',
    'RavenRecalibratedExplosives',
    'ShieldWall',
    'SmartServos',
    'Stimpack',
    'StrikeCannons',
    'TerranBuildingArmor',
    'TerranInfantryArmorsLevel1',
    'TerranInfantryArmorsLevel2',
    'TerranInfantryArmorsLevel3',
    'TerranInfantryWeaponsLevel1',
    'TerranInfantryWeaponsLevel2',
    'TerranInfantryWeaponsLevel3',
    'TerranShipArmorsLevel1',
    'TerranShipArmorsLevel2',
    'TerranShipArmorsLevel3',
    'TerranShipWeaponsLevel1',
    'TerranShipWeaponsLevel2',
    'TerranShipWeaponsLevel3',
    'TerranVehicleAndShipArmorsLevel1',
    'TerranVehicleAndShipArmorsLevel2',
    'TerranVehicleAndShipArmorsLevel3',
    'TerranVehicleAndShipWeaponsLevel1',
    'TerranVehicleAndShipWeaponsLevel2',
    'TerranVehicleAndShipWeaponsLevel3',
    'TerranVehicleArmorsLevel1',
    'TerranVehicleArmorsLevel2',
    'TerranVehicleArmorsLevel3',
    'TerranVehicleWeaponsLevel1',
    'TerranVehicleWeaponsLevel2',
    'TerranVehicleWeaponsLevel3',
    'TransformationServos',
    'TunnelingClaws',
    'VoidRaySpeedUpgrade',
    'WarpGateResearch',
    'ZergFlyerArmorsLevel1',
    'ZergFlyerArmorsLevel2',
    'ZergFlyerArmorsLevel3',
    'ZergFlyerWeaponsLevel1',
    'ZergFlyerWeaponsLevel2',
    'ZergFlyerWeaponsLevel3',
    'ZergGroundArmorsLevel1',
    'ZergGroundArmorsLevel2',
    'ZergGroundArmorsLevel3',
    'ZergMeleeWeaponsLevel1',
    'ZergMeleeWeaponsLevel2',
    'ZergMeleeWeaponsLevel3',
    'ZergMissileWeaponsLevel1',
    'ZergMissileWeaponsLevel2',
    'ZergMissileWeaponsLevel3',
    'hydraliskspeed',
    'overlordspeed',
    'overlordtransport',
    'zerglingattackspeed',
    'zerglingmovementspeed',
])